apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netsek-cr
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create","delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingress,networkpolicy"]
  verbs: ["watch", "list","create","delete"]