ClusterapiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netsek-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netsek-cr
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: netsek-sa