apiVersion: cache.drizzle.com/v1alpha1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/managed-by: kustomize
  name: memcached-sample
spec:
  # TODO(user): Add fields here
  size: 1
